### PR TITLE
Tickets/instrm 735

### PR DESCRIPTION
**Pull request by alefur**
I'm currently changing ICS code to use your library, I just have a remark about exceptions.
Any particular reason to catch the exception when a transaction error occurs ?
Rolling back the session is definitely a good idea, but I would still raise the exception. 
ICS kind of need those information, to narrow down the issue.

### CODE REVIEW

**Comment by alefur** [comment]
I'm proposing those changes, cf last commit.
Tell me if that's okay with you.

**Comment by kiyoyabe** [comment]
These changes are fine to me. Thanks.

**Comment by alefur** [comment]
great ! Do you need to add any more things to this branch or shall I merge ?

**Comment by kiyoyabe** [comment]
I think we can close this ticket. We should create new ones if we need to add more.

**Pull request merged**
