### PR TITLE
fix: "Undefined variable" errors

### PR DESCRIPTION
**Pull request by michitaro**
This PR is for fixing some typos in `opdb.models`.

`opdb.py` also has some errors detected by `pylint`, but I don't know how to fix them.

```bash
$ ./.venv/bin/pylint --errors-only opdb
************* Module opdb.opdb
python/opdb/opdb.py:37:27: E1101: Module 'opdb.models' has no 'tel_condition' member (no-member)
python/opdb/opdb.py:39:27: E1101: Module 'opdb.models' has no 'tel_visit' member (no-member)
python/opdb/opdb.py:1135:29: E1101: Module 'opdb.models' has no 'tel_visit' member (no-member)
python/opdb/opdb.py:1164:43: E1101: Module 'opdb.models' has no 'tel_visit' member (no-member)
python/opdb/opdb.py:1164:68: E1101: Module 'opdb.models' has no 'tel_visit' member (no-member)
python/opdb/opdb.py:1787:4: E0102: method already defined line 865 (function-redefined)
```

I think `tel_condition` is renamed to `tel_status`? but I'm not sure.

### CODE REVIEW

**Comment by kiyoyabe** [comment]
Sorry variable names are correct. I made a mistake after that. The following should be correct.

        self.guide_delta_az = guide_delta_az
        self.guide_delta_el = guide_delta_el
        self.guide_delta_z = guide_delta_z
        self.guide_delta_z1 = guide_delta_z1
        self.guide_delta_z2 = guide_delta_z2
        self.guide_delta_z3 = guide_delta_z3
        self.guide_delta_z4 = guide_delta_z4
        self.guide_delta_z5 = guide_delta_z5
        self.guide_delta_z6 = guide_delta_z6

**Comment by michitaro** [comment]
OK. I will make them as you suggested.

**Comment by kiyoyabe** [comment]
And we do not have `tel_condition` & `tel_visit` anymore.

**Comment by michitaro** [comment]
I have changed the parameter names.

**Comment by kiyoyabe** [comment]
Should we do something like this?
        self.guide_delta_az = guide_delta_az

**Comment by michitaro** [comment]
Oh, I should change the property names too.
I've force pushed the codes.

**Comment by kiyoyabe** [comment]
Thank you. The changes look good.

**Pull request merged**
