### PR TITLE
Tickets/instrm 1207

### PR DESCRIPTION
**Pull request by kiyoyabe**
- added `annotation_id` and `created_at` in `sps_annotation`
- added some comments in `sps_` tables for informativeness

### CODE REVIEW

**Review by alefur — CHANGES_REQUESTED** [review]
I would only change annotation_id with :
`autoincrement=True`
it's really just an index.
Otherwise, it's all good to me.
Thanks.

**Comment by kiyoyabe** [comment]
> I would only change annotation_id with :
> `autoincrement=True`
> it's really just an index.
> Otherwise, it's all good to me.
> Thanks.

fixed it.

**Comment by kiyoyabe** [comment]
@alefur Do you want to update the schema on the mountain soon?

**Comment by alefur** [comment]
The sooner the better I think. 
How do you proceed with schema evolution these days ?

**Comment by kiyoyabe** [comment]
I use _alembic_ as usual. I have already tested for the latest change. The change of primary key with auto_increment was a little bit tricky, but I believe I found the solution. Anyway, I'll try to make change tomorrow.

**Pull request merged**
